#!/bin/bash

crop() {
	local sFile="$1"
	mogrify -gravity North -crop 33x60% "$sFile"
}

render() {
	local sInput="$1"
	local fClock="$2"
	local sOutput="$3"
	if [ -z "$sOutput" ]
	then
		sOutput="${sInput}_$fClock"
	fi
	local sFrame
	local bPreview
	if [ "$fClock" -ge 1000 ]
	then
		bPreview=1
	else
		bPreview=0
	fi
	mkdir -p output
	if [ $bPreview == 1 ]
	then
		povray -I$sInput.pov -SR0.0 -ER0.60 -SC0.33 -EC0.67 -W1024 -H768 -D0 +UA +Q9 +A0.2 +K$fClock -Ooutput/$sOutput.png
		crop output/$sOutput.png
		display output/$sOutput.png
	else
		povray -I$sInput.pov -W1024 -H768 +UA +Q9 +A0.8 +K$fClock +P -Ooutput/$sOutput.png
	fi
}

render $*
