#!/bin/bash

crop() {
	local sFile="$1"
	mogrify -gravity North -crop 33x60% "$sFile"
}


# renvoie un nom de fichier affublé d'une extension, si cette dernière
# n'est pas déjà présente à la fin du nom de fichier
# @example appendFileExtension mon_fichier pov --> mon_fichier.pov
# @example appendFileExtension mon_fichier.pov pov --> mon_fichier.pov (inchangé)
# @param $1 racine du nom de fichier
# @param $2 extension souhaitée
# @return nom de fichier completé par l'extension
appendFileExtension() {
	local sFileName="$1"
	local sFileExt=".$2"
	echo "${sFileName%$sFileExt}$sFileExt"
}

render() {
	local sInput=`appendFileExtension "$1" "pov"`
	local fClock="$2"
	local sOutput="${sInput}_$fClock"
	local sFrame
	local bPreview
	local bBatch
	local sPause
	mkdir -p output
	povray -I$sInput -W512 -H384 +UA +Q9 +A0.8 +K$fClock -D0 -GA -Ooutput/$sOutput.png 2> /dev/null
}

renderPreview() {
	local sInput=`appendFileExtension "$1" "pov"`
	local fClock="$2"
	local sOutput="${sInput}_$fClock"
	local sFrame
	local bPreview
	local bBatch
	local sPause
	if [ "$fClock" -ge 1000 ]
	then
		bOrth=1
	else
		bOrth=0
	fi
	mkdir -p output
	if [ $bOrth == 1 ]
	then
		povray -I$sInput -SR0.0 -ER0.60 -SC0.33 -EC0.67 -W1024 -H768 -D0 +UA +Q9 +A0.2 +K$fClock -D0 -Ooutput/$sOutput.png
		local nError=$?
		if [ $nError -ne 0 ]
		then
			echo There was an error.
		else
			crop output/$sOutput.png
			display output/$sOutput.png
		fi
	else
		povray -I$sInput -W1024 -H768 +UA +Q9 +A0.8 +K$fClock +P -Ooutput/$sOutput.png
	fi
}

renderAllFrames() {
	local sFile="$1"
	local nDir="$2"
	local nStop="$3"
	local i
	local nFrame
	for i in `seq 0 $nStop`
	do
		nFrame=$i
		if [ "$nFrame" -le 10 ]
		then
			nFrame=0$nFrame
		fi
		render "$sFile" $nDir$nFrame
		echo -en "▶"
	done
}

renderAllDirections() {
	local sFile=`appendFileExtension "$1" "pov"`
	local nStop=`grep -oe "@frames \\+[0-9]\\+" $sFile| awk '{print $2}'`
	local i
	local nFrame
	local nFrames=`expr 8 "*" "(" $nStop + 1 ")"`
	echo "rendering : $sFile"
	echo "first frame : 0"
	echo "last frame : $nStop"
	echo "total frames : $nFrames"
	for i in `seq 1 $nFrames`
	do
		echo -en "▷"
	done
	echo -en \\r
	for i in `seq 0 7`
	do
		renderAllFrames $sFile $i $nStop
	done
	echo " "
	echo "done"
}

sCommand="$1"
shift
case $sCommand in 
	-r)
		sInput="$1"
		renderAllDirections "$sInput"
	;;
	
	-p)
		renderPreview $*
	;;
	
	*)
		echo "first parameter must be :"
		echo "   -p preview"
		echo "   -r render all frames"
	;;
esac
