#!/bin/bash

render() {
	sInput="$1"
	fClock="$2"
	sOutput="$3"
	if [ -z "$sOutput" ]
	then
		sOutput="${sInput}_$fClock"
	fi
	mkdir -p output
	povray -I$sInput.pov -W1024 -H768 +UA +Q9 +A0.4 +K$fClock +P -Ooutput/$sOutput.png
}

render $*
