#ifndef(T_Legs)
	#declare T_Legs = texture {
		pigment {
			Gray50
		}
	}
#end

#ifndef(T_Torso)
	#declare T_Torso = texture {
		pigment {
			Gray50
		}
	}
#end

#ifndef(T_Arms)
	#declare T_Arms = texture {
		pigment {
			Gray50
		}
	}
#end

#ifndef(T_Skin)
	#declare T_Skin = texture {
		pigment {
			Gray50
		}
	}
#end

#ifndef(T_Head)
	#declare T_Head = texture {
		pigment {
			Gray50
		}
	}
#end
